obstacle_range: 6.0
raytrace_range: 8.5
footprint: [[0.35,0.25],[0.35,-0.25],[-0.5,0]]
map_topic: /map
subscribe_to_update: true
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser,data_type: LaserScan, topic: scan_filtered,marking: true , clearing: true }
always_send_full_costmap: true

